# Generated by Django 4.2.9 on 2024-06-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Products", new_name="Product",),
    ]
