# Generated by Django 4.2.9 on 2024-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_rename_products_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(blank=True, upload_to="upload"),
        ),
    ]
