# Generated by Django 4.2.9 on 2024-06-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_product_images_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ImageField(blank=True, upload_to="upload"),
        ),
        migrations.DeleteModel(name="ProductImage",),
    ]
